"""Shared HintBench constants."""

REQUEST_LOG_ENABLED = True
REQUEST_LOG_EVERY = 1
# REQUEST_LOG_MODE = "compact"
# REQUEST_LOG_MODE = "single_line"
REQUEST_LOG_MODE = "full"

CONVERTED_MESSAGE_LOG_ENABLED = True
CONVERTED_MESSAGE_LOG_EVERY = REQUEST_LOG_EVERY
CONVERTED_MESSAGE_LOG_MODE = REQUEST_LOG_MODE

HINT_INJECTION_LOG_ENABLED = True
HINT_INJECTION_LOG_EVERY = REQUEST_LOG_EVERY
HINT_INJECTION_LOG_MODE = REQUEST_LOG_MODE

REQUEST_DISPATCH_LOG_ENABLED = True
REQUEST_DISPATCH_LOG_EVERY = REQUEST_LOG_EVERY
REQUEST_DISPATCH_LOG_MODE = REQUEST_LOG_MODE
