#!/usr/bin/env bash

# Machine-readable cache-pinning microbenchmark contract.
# Source this file when you want the cache-pinning microbenchmark to inherit
# its real defaults from one place.

CONTRACT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="${ROOT_DIR:-$(cd "${CONTRACT_DIR}/.." && pwd)}"
MACHINE_PROFILE="${DYNAMO_MACHINE_PROFILE:-default}"

# Public wrapper behavior
: "${CACHE_PINNING_MODE:=all}"
: "${CACHE_PINNING_ID:=cache_pinning_microbenchmark_$(date +%Y%m%d_%H%M%S)}"
: "${EXPERIMENT_RESET_MODE:=restart}"

# Pinned isolated upstream stack
: "${CACHE_PINNING_DYNAMO_SOURCE_REPO:=https://github.com/ai-dynamo/dynamo.git}"
: "${CACHE_PINNING_DYNAMO_PULL_REF:=6213}"
: "${CACHE_PINNING_DYNAMO_SOURCE_REF:=7d3d4ec8e4ae865af2f903b21b4afabca28e1940}"
: "${CACHE_PINNING_DYNAMO_SOURCE_DIR:=${ROOT_DIR}/upstream/dynamo_cache_pinning}"

: "${CACHE_PINNING_SGLANG_SOURCE_REPO:=https://github.com/sgl-project/sglang.git}"
: "${CACHE_PINNING_SGLANG_PULL_REF:=18941}"
: "${CACHE_PINNING_SGLANG_SOURCE_REF:=ff2f70b0fcb6b3ea130c46927ed98edf69d5c17c}"
: "${CACHE_PINNING_SGLANG_SOURCE_DIR:=${ROOT_DIR}/upstream/sglang_cache_pinning}"
: "${CACHE_PINNING_SGLANG_ROOT:=${CACHE_PINNING_SGLANG_SOURCE_DIR}/python/sglang}"

# Isolated cache-pinning images
: "${CACHE_PINNING_FRONTEND_IMAGE:=local/dynamo-frontend:cache-pinning-${MACHINE_PROFILE}}"
: "${CACHE_PINNING_WORKER_IMAGE:=local/dynamo-sglang:cache-pinning-${MACHINE_PROFILE}}"
: "${CACHE_PINNING_EPP_IMAGE:=registry.k8s.io/gateway-api-inference-extension/epp:v0.5.1}"

# Frontend cache-control contract
: "${CACHE_PINNING_FRONTEND_FLAG_MODE:=auto}"
: "${CACHE_PINNING_FRONTEND_FLAG_VALUE:=--enable-cache-control}"
: "${CACHE_PINNING_ENABLE_CACHE_CONTROL:=1}"
: "${CACHE_PINNING_ROUTER_MODE:=kv}"

# Shared cache-pinning knobs
: "${CACHE_PINNING_REQUEST_TYPE:=ephemeral}"
: "${CACHE_PINNING_TTL:=1h}"
: "${CACHE_PINNING_TTL_MIN_SECONDS:=300}"
: "${CACHE_PINNING_TTL_MAX_SECONDS:=3600}"
: "${CACHE_PINNING_PINNED_RATIO:=0.1}"
: "${SGLANG_HICACHE_MAX_PINNED_RATIO:=${CACHE_PINNING_PINNED_RATIO}}"
: "${CACHE_PINNING_HICACHE_RATIO:=1}"
: "${CACHE_PINNING_HICACHE_WRITE_POLICY:=write_through}"
: "${CACHE_PINNING_MEM_FRACTION_STATIC:=0.7}"
: "${CACHE_PINNING_ENABLE_CACHE_REPORT:=1}"
: "${CACHE_PINNING_ENABLE_HIERARCHICAL_CACHE:=1}"
: "${CACHE_PINNING_REQUIRE_HIERARCHICAL_CACHE:=1}"
: "${CACHE_PINNING_DEVELOPMENT_BRANCH_STACK:=1}"
: "${AUTO_BUILD_CACHE_PINNING_IMAGES:=1}"
: "${CACHE_PINNING_REBUILD_IMAGES:=0}"

# Validation-mode defaults
: "${CACHE_PINNING_TURN1_MAX_TOKENS:=128}"
: "${CACHE_PINNING_TURN2_MAX_TOKENS:=128}"

# Sweep-mode defaults
: "${RETENTION_ATTRIBUTION_MODE:=light}"
: "${RETENTION_REQUEST_CONTEXT_MODE:=disable}"
: "${RETENTION_TOP_LEVEL_PRIORITY_MODE:=disable}"
: "${KV_TIER_MODES:=gpu_cpu}"
: "${CONTROL_HINT_PROFILE:=none}"
: "${PROTECTED_HINT_PROFILES:=none}"
: "${CONTROL_CACHE_CONTROL_PROFILE:=off}"
: "${PROTECTED_CACHE_CONTROL_PROFILES:=ephemeral:1h}"
: "${DISTRACTOR_CACHE_CONTROL_PROFILE:=off}"
: "${DISTRACTOR_COUNTS:=20 40 60 80}"
: "${PROTECTED_INPUT_LEN:=500}"
: "${DISTRACTOR_INPUT_LEN:=200}"
: "${RANDOM_OUTPUT_LEN:=1}"
: "${MAX_CONTEXT_TOKENS:=17146}"
: "${SGLANG_TRANSFER_LOG_PROFILE:=off}"
: "${WORKER_BASE_ARGS:=--enable-cache-report --radix-eviction-policy lru}"

# Recommended readiness defaults
: "${MODEL_READY_RETRIES:=900}"
: "${MODEL_READY_DELAY_SECS:=3}"
: "${MODEL_READY_STABLE_HITS:=2}"
: "${MODEL_SMOKE_RETRIES:=180}"
: "${MODEL_SMOKE_DELAY_SECS:=15}"
: "${MODEL_COOLDOWN_SECS:=60}"

export ROOT_DIR
export MACHINE_PROFILE
export CACHE_PINNING_MODE
export CACHE_PINNING_ID
export EXPERIMENT_RESET_MODE
export CACHE_PINNING_DYNAMO_SOURCE_REPO
export CACHE_PINNING_DYNAMO_PULL_REF
export CACHE_PINNING_DYNAMO_SOURCE_REF
export CACHE_PINNING_DYNAMO_SOURCE_DIR
export CACHE_PINNING_SGLANG_SOURCE_REPO
export CACHE_PINNING_SGLANG_PULL_REF
export CACHE_PINNING_SGLANG_SOURCE_REF
export CACHE_PINNING_SGLANG_SOURCE_DIR
export CACHE_PINNING_SGLANG_ROOT
export CACHE_PINNING_FRONTEND_IMAGE
export CACHE_PINNING_WORKER_IMAGE
export CACHE_PINNING_EPP_IMAGE
export CACHE_PINNING_FRONTEND_FLAG_MODE
export CACHE_PINNING_FRONTEND_FLAG_VALUE
export CACHE_PINNING_ENABLE_CACHE_CONTROL
export CACHE_PINNING_ROUTER_MODE
export CACHE_PINNING_REQUEST_TYPE
export CACHE_PINNING_TTL
export CACHE_PINNING_TTL_MIN_SECONDS
export CACHE_PINNING_TTL_MAX_SECONDS
export CACHE_PINNING_PINNED_RATIO
export SGLANG_HICACHE_MAX_PINNED_RATIO
export CACHE_PINNING_HICACHE_RATIO
export CACHE_PINNING_HICACHE_WRITE_POLICY
export CACHE_PINNING_MEM_FRACTION_STATIC
export CACHE_PINNING_ENABLE_CACHE_REPORT
export CACHE_PINNING_ENABLE_HIERARCHICAL_CACHE
export CACHE_PINNING_REQUIRE_HIERARCHICAL_CACHE
export CACHE_PINNING_DEVELOPMENT_BRANCH_STACK
export AUTO_BUILD_CACHE_PINNING_IMAGES
export CACHE_PINNING_REBUILD_IMAGES
export CACHE_PINNING_TURN1_MAX_TOKENS
export CACHE_PINNING_TURN2_MAX_TOKENS
export RETENTION_ATTRIBUTION_MODE
export RETENTION_REQUEST_CONTEXT_MODE
export RETENTION_TOP_LEVEL_PRIORITY_MODE
export KV_TIER_MODES
export CONTROL_HINT_PROFILE
export PROTECTED_HINT_PROFILES
export CONTROL_CACHE_CONTROL_PROFILE
export PROTECTED_CACHE_CONTROL_PROFILES
export DISTRACTOR_CACHE_CONTROL_PROFILE
export DISTRACTOR_COUNTS
export PROTECTED_INPUT_LEN
export DISTRACTOR_INPUT_LEN
export RANDOM_OUTPUT_LEN
export MAX_CONTEXT_TOKENS
export SGLANG_TRANSFER_LOG_PROFILE
export WORKER_BASE_ARGS
export MODEL_READY_RETRIES
export MODEL_READY_DELAY_SECS
export MODEL_READY_STABLE_HITS
export MODEL_SMOKE_RETRIES
export MODEL_SMOKE_DELAY_SECS
export MODEL_COOLDOWN_SECS
