#!/usr/bin/env bash

# Machine-readable priority-scheduling microbenchmark contract.

CONTRACT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="${ROOT_DIR:-$(cd "${CONTRACT_DIR}/.." && pwd)}"
MACHINE_PROFILE="${DYNAMO_MACHINE_PROFILE:-default}"

# Public wrapper behavior
: "${PRIORITY_SCHEDULING_MODE:=all}"
: "${PRIORITY_SCHEDULING_ID:=priority_scheduling_microbenchmark_$(date +%Y%m%d_%H%M%S)}"

# Standard precise runtime stack
: "${PRIORITY_SCHEDULING_DYNAMO_SOURCE_DIR:=${ROOT_DIR}/upstream/dynamo}"
: "${PRIORITY_SCHEDULING_SGLANG_SOURCE_IMAGE:=lmsysorg/sglang:v0.5.11-cu129-runtime}"
: "${PRIORITY_SCHEDULING_SGLANG_SOURCE_DIR:=${ROOT_DIR}/upstream/sglang}"
: "${PRIORITY_SCHEDULING_SGLANG_ROOT:=${PRIORITY_SCHEDULING_SGLANG_SOURCE_DIR}/python/sglang}"
: "${PRIORITY_SCHEDULING_FRONTEND_IMAGE:=local/dynamo-frontend:runtime-json-logs-${MACHINE_PROFILE}}"
: "${PRIORITY_SCHEDULING_WORKER_IMAGE:=local/dynamo-sglang:runtime-json-logs-${MACHINE_PROFILE}}"

# Public wrapper and helper paths
: "${PRIORITY_SCHEDULING_PUBLIC_WRAPPER:=${ROOT_DIR}/agentbench/run_priority_scheduling_microbenchmark_single_host.sh}"
: "${PRIORITY_SCHEDULING_PROBE_HELPER:=${ROOT_DIR}/agentbench/run_priority_scheduling_probe_single_host.sh}"

# Probe defaults
: "${PRIORITY_SCHEDULING_ATTRIBUTION_MODE:=precise}"
: "${PRIORITY_REQUEST_CONTEXT_MODE:=auto}"
: "${PRIORITY_TOP_LEVEL_PRIORITY_MODE:=auto}"
: "${EXPERIMENT_RESET_MODE:=restart}"
: "${LOW_PRIORITY_COUNT:=8}"
: "${HIGH_PRIORITY_COUNT:=4}"
: "${LOW_PRIORITY_VALUE:=1}"
: "${HIGH_PRIORITY_VALUE:=10}"
: "${PRIORITY_HINT_KIND:=priority}"
: "${LOW_LATENCY_SENSITIVITY_VALUE:=0.2}"
: "${HIGH_LATENCY_SENSITIVITY_VALUE:=1.0}"
: "${PRIORITY_INPUT_LEN:=4000}"
: "${PRIORITY_OUTPUT_LEN:=128}"
: "${PRIORITY_ARRIVAL_GAP_MS:=200}"
: "${PRIORITY_INTER_REQUEST_GAP_MS:=20}"
: "${PRIORITY_SCHEDULING_SWEEP_AXIS:=PRIORITY_ARRIVAL_GAP_MS}"
: "${PRIORITY_SCHEDULING_SWEEP_VALUES:=50 100 200 400}"
: "${PRIORITY_SCHEDULING_SWEEP_SEED_MODE:=per_value}"
: "${PRIORITY_REQUEST_SOURCE:=synthetic}"
: "${PRIORITY_SWEBENCH_DATASET:=ScaleAI/SWE-bench_Pro}"
: "${PRIORITY_SWEBENCH_SPLIT:=test}"
: "${PRIORITY_SWEBENCH_START_INDEX:=0}"
: "${PRIORITY_SWEBENCH_ALLOW_REUSE:=0}"
: "${RETENTION_PROMPT_ISOLATION_MODE:=disjoint}"
: "${REQUEST_TIMEOUT:=600}"
: "${SGLANG_TRANSFER_LOG_PROFILE:=full}"
: "${WORKER_BASE_ARGS:=--enable-cache-report --enable-priority-scheduling --radix-eviction-policy priority}"
: "${IGNORE_EOS:=0}"
: "${AUTO_BUILD_PRECISE_IMAGES:=1}"
: "${STOP_DYNAMO_WHEN_DONE:=1}"

# Readiness defaults
: "${MODEL_READY_RETRIES:=900}"
: "${MODEL_READY_DELAY_SECS:=3}"
: "${MODEL_READY_STABLE_HITS:=2}"
: "${MODEL_SMOKE_RETRIES:=180}"
: "${MODEL_SMOKE_DELAY_SECS:=15}"
: "${MODEL_COOLDOWN_SECS:=60}"

# Reporting defaults
: "${PRIORITY_SCHEDULING_REPORT_DIR:=${ROOT_DIR}/experiments/reports/priority_scheduling_microbenchmark}"
: "${PRIORITY_SCHEDULING_LATEST_PREFIX:=${ROOT_DIR}/experiments/reports/latest_priority_scheduling_microbenchmark}"
: "${PRIORITY_SCHEDULING_LATEST_MATRIX:=${PRIORITY_SCHEDULING_LATEST_PREFIX}_matrix.csv}"
: "${PRIORITY_SCHEDULING_LATEST_SUMMARY_MD:=${PRIORITY_SCHEDULING_LATEST_PREFIX}_summary.md}"
: "${PRIORITY_SCHEDULING_LATEST_RUN_CONTRACT:=${PRIORITY_SCHEDULING_LATEST_PREFIX}_run_contract.json}"
: "${PRIORITY_SCHEDULING_LATEST_JUMP_AHEAD_CHART:=${PRIORITY_SCHEDULING_LATEST_PREFIX}_jump_ahead.svg}"

export ROOT_DIR
export MACHINE_PROFILE
export PRIORITY_SCHEDULING_MODE
export PRIORITY_SCHEDULING_ID
export PRIORITY_SCHEDULING_DYNAMO_SOURCE_DIR
export PRIORITY_SCHEDULING_SGLANG_SOURCE_IMAGE
export PRIORITY_SCHEDULING_SGLANG_SOURCE_DIR
export PRIORITY_SCHEDULING_SGLANG_ROOT
export PRIORITY_SCHEDULING_FRONTEND_IMAGE
export PRIORITY_SCHEDULING_WORKER_IMAGE
export PRIORITY_SCHEDULING_PUBLIC_WRAPPER
export PRIORITY_SCHEDULING_PROBE_HELPER
export PRIORITY_SCHEDULING_ATTRIBUTION_MODE
export PRIORITY_REQUEST_CONTEXT_MODE
export PRIORITY_TOP_LEVEL_PRIORITY_MODE
export EXPERIMENT_RESET_MODE
export LOW_PRIORITY_COUNT
export HIGH_PRIORITY_COUNT
export LOW_PRIORITY_VALUE
export HIGH_PRIORITY_VALUE
export PRIORITY_HINT_KIND
export LOW_LATENCY_SENSITIVITY_VALUE
export HIGH_LATENCY_SENSITIVITY_VALUE
export PRIORITY_INPUT_LEN
export PRIORITY_OUTPUT_LEN
export PRIORITY_ARRIVAL_GAP_MS
export PRIORITY_INTER_REQUEST_GAP_MS
export PRIORITY_SCHEDULING_SWEEP_AXIS
export PRIORITY_SCHEDULING_SWEEP_VALUES
export PRIORITY_SCHEDULING_SWEEP_SEED_MODE
export PRIORITY_REQUEST_SOURCE
export PRIORITY_SWEBENCH_DATASET
export PRIORITY_SWEBENCH_SPLIT
export PRIORITY_SWEBENCH_START_INDEX
export PRIORITY_SWEBENCH_ALLOW_REUSE
export RETENTION_PROMPT_ISOLATION_MODE
export REQUEST_TIMEOUT
export SGLANG_TRANSFER_LOG_PROFILE
export WORKER_BASE_ARGS
export IGNORE_EOS
export AUTO_BUILD_PRECISE_IMAGES
export STOP_DYNAMO_WHEN_DONE
export MODEL_READY_RETRIES
export MODEL_READY_DELAY_SECS
export MODEL_READY_STABLE_HITS
export MODEL_SMOKE_RETRIES
export MODEL_SMOKE_DELAY_SECS
export MODEL_COOLDOWN_SECS
export PRIORITY_SCHEDULING_REPORT_DIR
export PRIORITY_SCHEDULING_LATEST_PREFIX
export PRIORITY_SCHEDULING_LATEST_MATRIX
export PRIORITY_SCHEDULING_LATEST_SUMMARY_MD
export PRIORITY_SCHEDULING_LATEST_RUN_CONTRACT
export PRIORITY_SCHEDULING_LATEST_JUMP_AHEAD_CHART
