#!/usr/bin/env bash

# Machine-readable speculative-prefill microbenchmark contract.

CONTRACT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="${ROOT_DIR:-$(cd "${CONTRACT_DIR}/.." && pwd)}"
MACHINE_PROFILE="${DYNAMO_MACHINE_PROFILE:-default}"

# Public wrapper behavior
: "${SPEC_PREFILL_MODE:=all}"
: "${SPEC_PREFILL_ID:=speculative_prefill_microbenchmark_$(date +%Y%m%d_%H%M%S)}"

# Standard precise runtime stack
: "${SPEC_PREFILL_DYNAMO_SOURCE_DIR:=${ROOT_DIR}/upstream/dynamo}"
: "${SPEC_PREFILL_SGLANG_SOURCE_IMAGE:=lmsysorg/sglang:v0.5.11-cu129-runtime}"
: "${SPEC_PREFILL_SGLANG_SOURCE_DIR:=${ROOT_DIR}/upstream/sglang}"
: "${SPEC_PREFILL_SGLANG_ROOT:=${SPEC_PREFILL_SGLANG_SOURCE_DIR}/python/sglang}"
: "${SPEC_PREFILL_FRONTEND_IMAGE:=local/dynamo-frontend:runtime-json-logs-${MACHINE_PROFILE}}"
: "${SPEC_PREFILL_WORKER_IMAGE:=local/dynamo-sglang:runtime-json-logs-${MACHINE_PROFILE}}"

# Public wrapper and helper paths
: "${SPEC_PREFILL_PUBLIC_WRAPPER:=${ROOT_DIR}/agentbench/run_speculative_prefill_microbenchmark_single_host.sh}"
: "${SPEC_PREFILL_PROBE_HELPER:=${ROOT_DIR}/agentbench/run_speculative_prefill_probe_single_host.sh}"

# Probe defaults
: "${SPEC_PREFILL_ATTRIBUTION_MODE:=precise}"
: "${SPEC_PREFILL_REQUEST_CONTEXT_MODE:=auto}"
: "${EXPERIMENT_RESET_MODE:=restart}"
: "${SPEC_PREFILL_TURN_A_WORDS:=4000}"
: "${SPEC_PREFILL_TURN_B_WORDS:=512}"
: "${SPEC_PREFILL_OUTPUT_TOKENS:=64}"
: "${SPEC_PREFILL_WARMUP_WAIT_MS:=500}"
: "${SPEC_PREFILL_SWEEP_AXIS:=SPEC_PREFILL_WARMUP_WAIT_MS}"
: "${SPEC_PREFILL_SWEEP_VALUES:=0 100 250 500 1000}"
: "${SPEC_PREFILL_SWEEP_SEED_MODE:=per_value}"
: "${SPEC_PREFILL_REQUEST_SOURCE:=synthetic}"
: "${SPEC_PREFILL_SWEBENCH_DATASET:=ScaleAI/SWE-bench_Pro}"
: "${SPEC_PREFILL_SWEBENCH_SPLIT:=test}"
: "${SPEC_PREFILL_TURN_A_INDEX:=0}"
: "${SPEC_PREFILL_TURN_B_INDEX:=1}"
: "${SPEC_PREFILL_SWEBENCH_PROTECTED_OFFSET:=2}"
: "${RETENTION_PROMPT_ISOLATION_MODE:=disjoint}"
: "${SGLANG_TRANSFER_LOG_PROFILE:=full}"
: "${WORKER_BASE_ARGS:=--enable-cache-report --enable-priority-scheduling --radix-eviction-policy priority}"
: "${AUTO_BUILD_PRECISE_IMAGES:=1}"
: "${STOP_DYNAMO_WHEN_DONE:=1}"

# Readiness defaults
: "${MODEL_READY_RETRIES:=900}"
: "${MODEL_READY_DELAY_SECS:=3}"
: "${MODEL_READY_STABLE_HITS:=2}"
: "${MODEL_SMOKE_RETRIES:=180}"
: "${MODEL_SMOKE_DELAY_SECS:=15}"
: "${MODEL_COOLDOWN_SECS:=60}"

# Reporting defaults
: "${SPEC_PREFILL_REPORT_DIR:=${ROOT_DIR}/experiments/reports/speculative_prefill_microbenchmark}"
: "${SPEC_PREFILL_LATEST_PREFIX:=${ROOT_DIR}/experiments/reports/latest_speculative_prefill_microbenchmark}"
: "${SPEC_PREFILL_LATEST_MATRIX:=${SPEC_PREFILL_LATEST_PREFIX}_matrix.csv}"
: "${SPEC_PREFILL_LATEST_SUMMARY_CSV:=${SPEC_PREFILL_LATEST_PREFIX}_summary.csv}"
: "${SPEC_PREFILL_LATEST_SUMMARY_MD:=${SPEC_PREFILL_LATEST_PREFIX}_summary.md}"
: "${SPEC_PREFILL_LATEST_RUN_CONTRACT:=${SPEC_PREFILL_LATEST_PREFIX}_run_contract.json}"
: "${SPEC_PREFILL_LATEST_TURNB_LATENCY_CHART:=${SPEC_PREFILL_LATEST_PREFIX}_turnb_latency.svg}"
: "${SPEC_PREFILL_LATEST_TURNB_CACHED_CHART:=${SPEC_PREFILL_LATEST_PREFIX}_turnb_cached.svg}"
: "${SPEC_PREFILL_LATEST_CHART_MANIFEST:=${SPEC_PREFILL_LATEST_PREFIX}_chart_manifest.json}"

export ROOT_DIR
export MACHINE_PROFILE
export SPEC_PREFILL_MODE
export SPEC_PREFILL_ID
export SPEC_PREFILL_DYNAMO_SOURCE_DIR
export SPEC_PREFILL_SGLANG_SOURCE_IMAGE
export SPEC_PREFILL_SGLANG_SOURCE_DIR
export SPEC_PREFILL_SGLANG_ROOT
export SPEC_PREFILL_FRONTEND_IMAGE
export SPEC_PREFILL_WORKER_IMAGE
export SPEC_PREFILL_PUBLIC_WRAPPER
export SPEC_PREFILL_PROBE_HELPER
export SPEC_PREFILL_ATTRIBUTION_MODE
export SPEC_PREFILL_REQUEST_CONTEXT_MODE
export EXPERIMENT_RESET_MODE
export SPEC_PREFILL_TURN_A_WORDS
export SPEC_PREFILL_TURN_B_WORDS
export SPEC_PREFILL_OUTPUT_TOKENS
export SPEC_PREFILL_WARMUP_WAIT_MS
export SPEC_PREFILL_SWEEP_AXIS
export SPEC_PREFILL_SWEEP_VALUES
export SPEC_PREFILL_SWEEP_SEED_MODE
export SPEC_PREFILL_REQUEST_SOURCE
export SPEC_PREFILL_SWEBENCH_DATASET
export SPEC_PREFILL_SWEBENCH_SPLIT
export SPEC_PREFILL_TURN_A_INDEX
export SPEC_PREFILL_TURN_B_INDEX
export SPEC_PREFILL_SWEBENCH_PROTECTED_OFFSET
export RETENTION_PROMPT_ISOLATION_MODE
export SGLANG_TRANSFER_LOG_PROFILE
export WORKER_BASE_ARGS
export AUTO_BUILD_PRECISE_IMAGES
export STOP_DYNAMO_WHEN_DONE
export MODEL_READY_RETRIES
export MODEL_READY_DELAY_SECS
export MODEL_READY_STABLE_HITS
export MODEL_SMOKE_RETRIES
export MODEL_SMOKE_DELAY_SECS
export MODEL_COOLDOWN_SECS
export SPEC_PREFILL_REPORT_DIR
export SPEC_PREFILL_LATEST_PREFIX
export SPEC_PREFILL_LATEST_MATRIX
export SPEC_PREFILL_LATEST_SUMMARY_CSV
export SPEC_PREFILL_LATEST_SUMMARY_MD
export SPEC_PREFILL_LATEST_RUN_CONTRACT
export SPEC_PREFILL_LATEST_TURNB_LATENCY_CHART
export SPEC_PREFILL_LATEST_TURNB_CACHED_CHART
export SPEC_PREFILL_LATEST_CHART_MANIFEST
