#!/usr/bin/env bash

# Shared AgentBench runtime defaults.
# Update AGENTBENCH_MODEL here when you want future runs to use a different model.

# AGENTBENCH_MODEL="${AGENTBENCH_MODEL:-Qwen/Qwen2.5-0.5B}"
AGENTBENCH_MODEL="${AGENTBENCH_MODEL:-Qwen/Qwen2.5-7B-Instruct}"
AGENTBENCH_FRONTEND_URL="${AGENTBENCH_FRONTEND_URL:-http://127.0.0.1:8000/v1/chat/completions}"
AGENTBENCH_MODEL_READY_RETRIES="${AGENTBENCH_MODEL_READY_RETRIES:-900}"
AGENTBENCH_MODEL_READY_DELAY_SECS="${AGENTBENCH_MODEL_READY_DELAY_SECS:-3}"
AGENTBENCH_MODEL_READY_STABLE_HITS="${AGENTBENCH_MODEL_READY_STABLE_HITS:-2}"
AGENTBENCH_MODEL_SMOKE_RETRIES="${AGENTBENCH_MODEL_SMOKE_RETRIES:-180}"
AGENTBENCH_MODEL_SMOKE_DELAY_SECS="${AGENTBENCH_MODEL_SMOKE_DELAY_SECS:-15}"
AGENTBENCH_MODEL_COOLDOWN_SECS="${AGENTBENCH_MODEL_COOLDOWN_SECS:-60}"

MODEL_READY_RETRIES="${MODEL_READY_RETRIES:-${AGENTBENCH_MODEL_READY_RETRIES}}"
MODEL_READY_DELAY_SECS="${MODEL_READY_DELAY_SECS:-${AGENTBENCH_MODEL_READY_DELAY_SECS}}"
MODEL_READY_STABLE_HITS="${MODEL_READY_STABLE_HITS:-${AGENTBENCH_MODEL_READY_STABLE_HITS}}"
MODEL_SMOKE_RETRIES="${MODEL_SMOKE_RETRIES:-${AGENTBENCH_MODEL_SMOKE_RETRIES}}"
MODEL_SMOKE_DELAY_SECS="${MODEL_SMOKE_DELAY_SECS:-${AGENTBENCH_MODEL_SMOKE_DELAY_SECS}}"
MODEL_COOLDOWN_SECS="${MODEL_COOLDOWN_SECS:-${AGENTBENCH_MODEL_COOLDOWN_SECS}}"

export AGENTBENCH_MODEL
export AGENTBENCH_FRONTEND_URL
export AGENTBENCH_MODEL_READY_RETRIES
export AGENTBENCH_MODEL_READY_DELAY_SECS
export AGENTBENCH_MODEL_READY_STABLE_HITS
export AGENTBENCH_MODEL_SMOKE_RETRIES
export AGENTBENCH_MODEL_SMOKE_DELAY_SECS
export AGENTBENCH_MODEL_COOLDOWN_SECS
export MODEL_READY_RETRIES
export MODEL_READY_DELAY_SECS
export MODEL_READY_STABLE_HITS
export MODEL_SMOKE_RETRIES
export MODEL_SMOKE_DELAY_SECS
export MODEL_COOLDOWN_SECS

agentbench_print_model_readiness_active_banner() {
  cat <<EOF
========================================
(3/6) MODEL READINESS ACTIVE (extended model wait and smoke timing are active)
========================================
MODEL_READY_RETRIES=${MODEL_READY_RETRIES}
MODEL_READY_DELAY_SECS=${MODEL_READY_DELAY_SECS}
MODEL_READY_STABLE_HITS=${MODEL_READY_STABLE_HITS}
MODEL_SMOKE_RETRIES=${MODEL_SMOKE_RETRIES}
MODEL_SMOKE_DELAY_SECS=${MODEL_SMOKE_DELAY_SECS}
MODEL_COOLDOWN_SECS=${MODEL_COOLDOWN_SECS}
EOF
}

agentbench_print_model_readiness_go_banner() {
  cat <<EOF
========================================
(5/6) MODEL READINESS GO (model registration and smoke test both passed)
========================================
EOF
}
