#!/usr/bin/env bash

# Shared AgentBench runtime defaults.
# Update AGENTBENCH_MODEL here when you want future runs to use a different model.

# AGENTBENCH_MODEL="${AGENTBENCH_MODEL:-Qwen/Qwen2.5-0.5B}"
AGENTBENCH_MODEL="${AGENTBENCH_MODEL:-Qwen/Qwen2.5-7B-Instruct}"
AGENTBENCH_FRONTEND_URL="${AGENTBENCH_FRONTEND_URL:-http://127.0.0.1:8000/v1/chat/completions}"
AGENTBENCH_MODEL_READY_RETRIES="${AGENTBENCH_MODEL_READY_RETRIES:-900}"
AGENTBENCH_MODEL_READY_DELAY_SECS="${AGENTBENCH_MODEL_READY_DELAY_SECS:-3}"
AGENTBENCH_MODEL_READY_STABLE_HITS="${AGENTBENCH_MODEL_READY_STABLE_HITS:-2}"
AGENTBENCH_MODEL_SMOKE_RETRIES="${AGENTBENCH_MODEL_SMOKE_RETRIES:-180}"
AGENTBENCH_MODEL_SMOKE_DELAY_SECS="${AGENTBENCH_MODEL_SMOKE_DELAY_SECS:-15}"
AGENTBENCH_MODEL_COOLDOWN_SECS="${AGENTBENCH_MODEL_COOLDOWN_SECS:-60}"
