#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

SUITE_CONFIG_PATH="${SUITE_CONFIG_PATH:-agentbench/agentic_hint_sweeps_suite.conf.sh}"
if [[ -f "${SUITE_CONFIG_PATH}" ]]; then
  # shellcheck disable=SC1090
  source "${SUITE_CONFIG_PATH}"
fi

SUITE_ID="${AGENTIC_HINT_SUITE_ID:-agentic_hint_sweeps_suite_$(date +%Y%m%d_%H%M%S)}"
SUITE_DIR="experiments/reports/agentic_hint_sweeps_suite/${SUITE_ID}"
NOHUP_LOG="${SUITE_DIR}/suite_nohup.log"
PID_FILE="${SUITE_DIR}/suite_nohup.pid"
LAUNCH_ENV_FILE="${SUITE_DIR}/suite_launch_env.sh"
LATEST_NOHUP_LINK="experiments/reports/latest_agentic_hint_sweeps_suite_nohup.log"
LATEST_NOHUP_ABS="$(pwd)/${LATEST_NOHUP_LINK}"
NOHUP_LOG_ABS="$(pwd)/${NOHUP_LOG}"
SUITE_INTERACTIVE_BUILD_PROGRESS="${SUITE_INTERACTIVE_BUILD_PROGRESS:-0}"

mkdir -p "${SUITE_DIR}"
: > "${NOHUP_LOG}"

cat > "${LAUNCH_ENV_FILE}" <<EOF
AGENTIC_HINT_SUITE_ID='${SUITE_ID}'
SUITE_CONFIG_PATH='${SUITE_CONFIG_PATH}'
DYNAMO_MACHINE_PROFILE='${DYNAMO_MACHINE_PROFILE:-}'
SUITE_MODEL='${SUITE_MODEL:-}'
SUITE_EXPERIMENTS='${SUITE_EXPERIMENTS:-}'
SUITE_CONTINUE_ON_ERROR='${SUITE_CONTINUE_ON_ERROR:-}'
SUITE_STOP_DYNAMO_BETWEEN_EXPERIMENTS='${SUITE_STOP_DYNAMO_BETWEEN_EXPERIMENTS:-}'
SUITE_ISOLATION_MODE='${SUITE_ISOLATION_MODE:-}'
SUITE_DEFAULT_MODE='${SUITE_DEFAULT_MODE:-}'
SUITE_INTERACTIVE_BUILD_PROGRESS='${SUITE_INTERACTIVE_BUILD_PROGRESS}'
SUITE_ENSURE_PRECISE_RUNTIME='${SUITE_ENSURE_PRECISE_RUNTIME:-}'
PRECISE_START_MODE='${PRECISE_START_MODE:-}'
EXPERIMENT_RESET_MODE='${EXPERIMENT_RESET_MODE:-}'
KV_RETENTION_MODE='${KV_RETENTION_MODE:-}'
RETENTION_SWEEP_SEED_MODE='${RETENTION_SWEEP_SEED_MODE:-}'
RETENTION_PROMPT_ISOLATION_MODE='${RETENTION_PROMPT_ISOLATION_MODE:-}'
RETENTION_ATTRIBUTION_MODE='${RETENTION_ATTRIBUTION_MODE:-}'
RETENTION_REQUEST_CONTEXT_MODE='${RETENTION_REQUEST_CONTEXT_MODE:-}'
RETENTION_TOP_LEVEL_PRIORITY_MODE='${RETENTION_TOP_LEVEL_PRIORITY_MODE:-}'
RETENTION_REQUEST_SOURCE='${RETENTION_REQUEST_SOURCE:-}'
RETENTION_SWEBENCH_DATASET='${RETENTION_SWEBENCH_DATASET:-}'
RETENTION_SWEBENCH_SPLIT='${RETENTION_SWEBENCH_SPLIT:-}'
RETENTION_SWEBENCH_INDEX='${RETENTION_SWEBENCH_INDEX:-}'
RETENTION_SWEBENCH_INSTANCE_ID='${RETENTION_SWEBENCH_INSTANCE_ID:-}'
RETENTION_SWEBENCH_DISTRACTOR_START_INDEX='${RETENTION_SWEBENCH_DISTRACTOR_START_INDEX:-}'
RETENTION_SWEBENCH_ALLOW_DISTRACTOR_REUSE='${RETENTION_SWEBENCH_ALLOW_DISTRACTOR_REUSE:-}'
KV_RETENTION_SWEEP_AXIS='${KV_RETENTION_SWEEP_AXIS:-}'
KV_RETENTION_SWEEP_VALUES='${KV_RETENTION_SWEEP_VALUES:-}'
DISTRACTOR_COUNTS='${DISTRACTOR_COUNTS:-}'
PROTECTED_INPUT_LEN='${PROTECTED_INPUT_LEN:-}'
DISTRACTOR_INPUT_LEN='${DISTRACTOR_INPUT_LEN:-}'
PROTECTED_HINT_PROFILES='${PROTECTED_HINT_PROFILES:-}'
SGLANG_TRANSFER_LOG='${SGLANG_TRANSFER_LOG:-}'
SGLANG_TRANSFER_LOG_PROFILE='${SGLANG_TRANSFER_LOG_PROFILE:-}'
CACHE_PINNING_MODE='${CACHE_PINNING_MODE:-}'
CACHE_PINNING_VALIDATE_TTL='${CACHE_PINNING_VALIDATE_TTL:-}'
CACHE_PINNING_SWEEP_VALUES='${CACHE_PINNING_SWEEP_VALUES:-}'
CACHE_PINNING_TTL='${CACHE_PINNING_TTL:-}'
CACHE_PINNING_PINNED_RATIO='${CACHE_PINNING_PINNED_RATIO:-}'
CACHE_PINNING_HICACHE_RATIO='${CACHE_PINNING_HICACHE_RATIO:-}'
PRIORITY_SCHEDULING_MODE='${PRIORITY_SCHEDULING_MODE:-}'
PRIORITY_SCHEDULING_SWEEP_AXIS='${PRIORITY_SCHEDULING_SWEEP_AXIS:-}'
PRIORITY_SCHEDULING_SWEEP_VALUES='${PRIORITY_SCHEDULING_SWEEP_VALUES:-}'
LOW_PRIORITY_COUNT='${LOW_PRIORITY_COUNT:-}'
HIGH_PRIORITY_COUNT='${HIGH_PRIORITY_COUNT:-}'
PRIORITY_INPUT_LEN='${PRIORITY_INPUT_LEN:-}'
PRIORITY_OUTPUT_LEN='${PRIORITY_OUTPUT_LEN:-}'
PRIORITY_INTER_REQUEST_GAP_MS='${PRIORITY_INTER_REQUEST_GAP_MS:-}'
PRIORITY_REQUEST_SOURCE='${PRIORITY_REQUEST_SOURCE:-}'
PRIORITY_SWEBENCH_DATASET='${PRIORITY_SWEBENCH_DATASET:-}'
PRIORITY_SWEBENCH_SPLIT='${PRIORITY_SWEBENCH_SPLIT:-}'
PRIORITY_SWEBENCH_START_INDEX='${PRIORITY_SWEBENCH_START_INDEX:-}'
PRIORITY_SWEBENCH_ALLOW_REUSE='${PRIORITY_SWEBENCH_ALLOW_REUSE:-}'
SPEC_PREFILL_MODE='${SPEC_PREFILL_MODE:-}'
SPEC_PREFILL_PROMPT_ISOLATION_MODE='${SPEC_PREFILL_PROMPT_ISOLATION_MODE:-}'
SPEC_PREFILL_SWEEP_SEED_MODE='${SPEC_PREFILL_SWEEP_SEED_MODE:-}'
SPEC_PREFILL_SWEEP_AXIS='${SPEC_PREFILL_SWEEP_AXIS:-}'
SPEC_PREFILL_SWEEP_VALUES='${SPEC_PREFILL_SWEEP_VALUES:-}'
SPEC_PREFILL_TURN_A_WORDS='${SPEC_PREFILL_TURN_A_WORDS:-}'
SPEC_PREFILL_TURN_B_WORDS='${SPEC_PREFILL_TURN_B_WORDS:-}'
SPEC_PREFILL_OUTPUT_TOKENS='${SPEC_PREFILL_OUTPUT_TOKENS:-}'
SPEC_PREFILL_REQUEST_SOURCE='${SPEC_PREFILL_REQUEST_SOURCE:-}'
SPEC_PREFILL_SWEBENCH_DATASET='${SPEC_PREFILL_SWEBENCH_DATASET:-}'
SPEC_PREFILL_SWEBENCH_SPLIT='${SPEC_PREFILL_SWEBENCH_SPLIT:-}'
SPEC_PREFILL_TURN_A_INDEX='${SPEC_PREFILL_TURN_A_INDEX:-}'
SPEC_PREFILL_TURN_B_INDEX='${SPEC_PREFILL_TURN_B_INDEX:-}'
SPEC_PREFILL_SWEBENCH_PROTECTED_OFFSET='${SPEC_PREFILL_SWEBENCH_PROTECTED_OFFSET:-}'
EXP9_MODE='${EXP9_MODE:-}'
EXP9_RETENTION_REQUEST_SOURCE='${EXP9_RETENTION_REQUEST_SOURCE:-}'
EXP9_RETENTION_SWEBENCH_DATASET='${EXP9_RETENTION_SWEBENCH_DATASET:-}'
EXP9_RETENTION_SWEBENCH_SPLIT='${EXP9_RETENTION_SWEBENCH_SPLIT:-}'
EXP9_RETENTION_SWEBENCH_INDEX='${EXP9_RETENTION_SWEBENCH_INDEX:-}'
EXP9_RETENTION_SWEBENCH_INSTANCE_ID='${EXP9_RETENTION_SWEBENCH_INSTANCE_ID:-}'
EXP9_RETENTION_SWEBENCH_DISTRACTOR_START_INDEX='${EXP9_RETENTION_SWEBENCH_DISTRACTOR_START_INDEX:-}'
EXP9_RETENTION_SWEBENCH_ALLOW_DISTRACTOR_REUSE='${EXP9_RETENTION_SWEBENCH_ALLOW_DISTRACTOR_REUSE:-}'
EXP9_RETENTION_TRAJECTORY_PROMPT_CATALOG='${EXP9_RETENTION_TRAJECTORY_PROMPT_CATALOG:-}'
EXP9_RETENTION_TRAJECTORY_PROTECTED_TASK_INDEX='${EXP9_RETENTION_TRAJECTORY_PROTECTED_TASK_INDEX:-}'
EXP9_RETENTION_TRAJECTORY_PROTECTED_INSTANCE_ID='${EXP9_RETENTION_TRAJECTORY_PROTECTED_INSTANCE_ID:-}'
EXP9_RETENTION_TRAJECTORY_PROTECTED_STAGE='${EXP9_RETENTION_TRAJECTORY_PROTECTED_STAGE:-}'
EXP9_RETENTION_TRAJECTORY_STAGES='${EXP9_RETENTION_TRAJECTORY_STAGES:-}'
EXP9_RETENTION_TRAJECTORY_DISTRACTOR_START_TASK_INDEX='${EXP9_RETENTION_TRAJECTORY_DISTRACTOR_START_TASK_INDEX:-}'
EXP9_RETENTION_TRAJECTORY_ALLOW_DISTRACTOR_REUSE='${EXP9_RETENTION_TRAJECTORY_ALLOW_DISTRACTOR_REUSE:-}'
EXP9_RETENTION_ATTRIBUTION_MODE='${EXP9_RETENTION_ATTRIBUTION_MODE:-}'
EXP9_RETENTION_REQUEST_CONTEXT_MODE='${EXP9_RETENTION_REQUEST_CONTEXT_MODE:-}'
EXP9_RETENTION_TOP_LEVEL_PRIORITY_MODE='${EXP9_RETENTION_TOP_LEVEL_PRIORITY_MODE:-}'
EXP9_STOP_ON_PROBE_FAILURE='${EXP9_STOP_ON_PROBE_FAILURE:-}'
EXP9_DISTRACTOR_COUNTS='${EXP9_DISTRACTOR_COUNTS:-}'
EXP9_PROTECTED_INPUT_LEN='${EXP9_PROTECTED_INPUT_LEN:-}'
EXP9_DISTRACTOR_INPUT_LEN='${EXP9_DISTRACTOR_INPUT_LEN:-}'
EXP9_PROTECTED_HINT_PROFILES='${EXP9_PROTECTED_HINT_PROFILES:-}'
EXP10_MODE='${EXP10_MODE:-}'
EXP10_DISTRACTOR_COUNTS='${EXP10_DISTRACTOR_COUNTS:-}'
EXP10_PROTECTED_INPUT_LEN='${EXP10_PROTECTED_INPUT_LEN:-}'
EXP10_DISTRACTOR_INPUT_LEN='${EXP10_DISTRACTOR_INPUT_LEN:-}'
EXP10_CACHE_PINNING_TTL='${EXP10_CACHE_PINNING_TTL:-}'
EXP10_CACHE_PINNING_PINNED_RATIO='${EXP10_CACHE_PINNING_PINNED_RATIO:-}'
EXP10_CACHE_PINNING_HICACHE_RATIO='${EXP10_CACHE_PINNING_HICACHE_RATIO:-}'
EXP11_MODE='${EXP11_MODE:-}'
EXP11_PRIORITY_REQUEST_SOURCE='${EXP11_PRIORITY_REQUEST_SOURCE:-}'
EXP11_PRIORITY_SWEBENCH_DATASET='${EXP11_PRIORITY_SWEBENCH_DATASET:-}'
EXP11_PRIORITY_SWEBENCH_SPLIT='${EXP11_PRIORITY_SWEBENCH_SPLIT:-}'
EXP11_PRIORITY_SWEBENCH_START_INDEX='${EXP11_PRIORITY_SWEBENCH_START_INDEX:-}'
EXP11_PRIORITY_SWEBENCH_ALLOW_REUSE='${EXP11_PRIORITY_SWEBENCH_ALLOW_REUSE:-}'
EXP11_PRIORITY_SCHEDULING_SWEEP_AXIS='${EXP11_PRIORITY_SCHEDULING_SWEEP_AXIS:-}'
EXP11_PRIORITY_SCHEDULING_SWEEP_VALUES='${EXP11_PRIORITY_SCHEDULING_SWEEP_VALUES:-}'
EXP11_LOW_PRIORITY_COUNT='${EXP11_LOW_PRIORITY_COUNT:-}'
EXP11_HIGH_PRIORITY_COUNT='${EXP11_HIGH_PRIORITY_COUNT:-}'
EXP11_PRIORITY_INPUT_LEN='${EXP11_PRIORITY_INPUT_LEN:-}'
EXP11_PRIORITY_OUTPUT_LEN='${EXP11_PRIORITY_OUTPUT_LEN:-}'
EXP11_PRIORITY_INTER_REQUEST_GAP_MS='${EXP11_PRIORITY_INTER_REQUEST_GAP_MS:-}'
EXP12_MODE='${EXP12_MODE:-}'
EXP12_SPEC_PREFILL_REQUEST_SOURCE='${EXP12_SPEC_PREFILL_REQUEST_SOURCE:-}'
EXP12_SPEC_PREFILL_SWEBENCH_DATASET='${EXP12_SPEC_PREFILL_SWEBENCH_DATASET:-}'
EXP12_SPEC_PREFILL_SWEBENCH_SPLIT='${EXP12_SPEC_PREFILL_SWEBENCH_SPLIT:-}'
EXP12_SPEC_PREFILL_TURN_A_INDEX='${EXP12_SPEC_PREFILL_TURN_A_INDEX:-}'
EXP12_SPEC_PREFILL_TURN_B_INDEX='${EXP12_SPEC_PREFILL_TURN_B_INDEX:-}'
EXP12_SPEC_PREFILL_SWEBENCH_PROTECTED_OFFSET='${EXP12_SPEC_PREFILL_SWEBENCH_PROTECTED_OFFSET:-}'
EXP12_SPEC_PREFILL_ATTRIBUTION_MODE='${EXP12_SPEC_PREFILL_ATTRIBUTION_MODE:-}'
EXP12_SPEC_PREFILL_REQUEST_CONTEXT_MODE='${EXP12_SPEC_PREFILL_REQUEST_CONTEXT_MODE:-}'
EXP12_SPEC_PREFILL_SWEEP_AXIS='${EXP12_SPEC_PREFILL_SWEEP_AXIS:-}'
EXP12_SPEC_PREFILL_SWEEP_VALUES='${EXP12_SPEC_PREFILL_SWEEP_VALUES:-}'
EXP12_SPEC_PREFILL_TURN_A_WORDS='${EXP12_SPEC_PREFILL_TURN_A_WORDS:-}'
EXP12_SPEC_PREFILL_TURN_B_WORDS='${EXP12_SPEC_PREFILL_TURN_B_WORDS:-}'
EXP12_SPEC_PREFILL_OUTPUT_TOKENS='${EXP12_SPEC_PREFILL_OUTPUT_TOKENS:-}'
EOF

nohup env AGENTIC_HINT_SUITE_ID="${SUITE_ID}" \
  SUITE_CONFIG_PATH="${SUITE_CONFIG_PATH}" \
  SUITE_INTERACTIVE_BUILD_PROGRESS="${SUITE_INTERACTIVE_BUILD_PROGRESS}" \
  EXPERIMENT_RESET_MODE="${EXPERIMENT_RESET_MODE:-}" \
  ./agentbench/run_agentic_hint_sweeps_suite_single_host.sh "$@" \
  > "${NOHUP_LOG}" 2>&1 < /dev/null &

PID=$!
printf '%s\n' "${PID}" > "${PID_FILE}"
ln -sfn "${NOHUP_LOG_ABS}" "${LATEST_NOHUP_ABS}"

cat <<EOF
Started agentic hint sweeps suite in the background.

suite_id: ${SUITE_ID}
pid: ${PID}
nohup_log: ${NOHUP_LOG}
latest_nohup_log: ${LATEST_NOHUP_LINK}
pid_file: ${PID_FILE}
launch_env: ${LAUNCH_ENV_FILE}
interactive_build_progress: ${SUITE_INTERACTIVE_BUILD_PROGRESS}

Watch the run:
  tail -f ${NOHUP_LOG}
  tail -f ${LATEST_NOHUP_LINK}

Check final outputs:
  cat ${SUITE_DIR}/suite_summary.md
  cat ${SUITE_DIR}/suite_manifest.json
  cat experiments/reports/latest_agentic_hint_sweeps_suite_summary.md
  cat experiments/reports/latest_agentic_hint_sweeps_suite_manifest.json

Stop it if needed:
  kill ${PID}
EOF
